channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.2
  - cffi==1.15.1
  - defusedxml==0.7.1
  - numpy==1.24.3
  - pandas==2.0.2
  - pillow==9.5.0
  - protobuf==3.20.3
  - requests==2.31.0
  - scipy==1.10.1
  - tensorflow==2.8.0
name: mlflow-env
